# Generated by Django 2.1.2 on 2018-10-24 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAdopcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Rescatado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotografia', models.FileField(blank=True, upload_to='')),
                ('razaPredominante', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perris.Estado')),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoVivienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.IntegerField(max_length=9)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=40)),
                ('fechaNacimiento', models.DateField()),
                ('telefono', models.IntegerField(max_length=9)),
                ('correo', models.EmailField(max_length=254)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perris.Ciudad')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perris.Region')),
                ('tipoUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perris.TipoUsuario')),
                ('tipoVivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perris.TipoVivienda')),
            ],
        ),
        migrations.AddField(
            model_name='registroadopcion',
            name='rescatado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perris.Rescatado'),
        ),
        migrations.AddField(
            model_name='registroadopcion',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perris.Usuario'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perris.Region'),
        ),
    ]
