# Generated by Django 2.1.2 on 2018-10-24 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perris', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='run',
            field=models.IntegerField(),
        ),
    ]
