# Generated by Django 2.1.2 on 2018-10-24 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perris', '0002_auto_20181023_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
