# Generated by Django 2.1.2 on 2018-10-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perris', '0003_auto_20181023_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tipoUsuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(default='DEFAULT', max_length=20),
        ),
    ]
