# Generated by Django 2.1.2 on 2018-10-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perris', '0004_auto_20181027_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipovivienda',
            name='nombre',
            field=models.CharField(max_length=40),
        ),
    ]
