# Generated by Django 2.1.2 on 2018-10-30 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perris', '0005_auto_20181029_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
